### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by himanku** [vaibhav-mougha/smelly-island-5345#7]
- [x] Make sure the UI is responsive
- [x] Make sure the components are well aligned
- [x] Make sure all the links are working fine
- [x] Create a readme documentation for the project repo
- [x] Submit the final product
